//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoyolBlog.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoneticiler
    {
        public int yonet_id { get; set; }
        public Nullable<int> uyeno { get; set; }
        public Nullable<bool> yetki { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
