//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoyolBlog.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int id { get; set; }
        public string yorum { get; set; }
        public Nullable<int> icerik_id { get; set; }
        public Nullable<int> uyeno { get; set; }
        public Nullable<System.DateTime> yorum_tarih { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Makaleler Makaleler { get; set; }
    }
}
